$(function(){
	$("#login").click(function(){
		$.ajax({
			url:"userServlet?cmd=doLogin",
			type:"post",
			dataType:"json",
			data:$("#loginForm").serialize(),
			success:function(resp){
				if(resp.state){
					alert("恭喜"+resp.user.realName+"登录了");
					location.href="views/superMain.jsp"
				}else{
					$(".panel-title").html(resp.tip);
				}
			}
		})
	});
})